### ISSUE TITLE
Ensure gold is not wasted when lives cap is reached

### ISSUE THREAD

**Issue by Kirschgeschmack** [nvs/gem#256]
__Map version:__ Gem TD+ 1.3.1
__Replay(s):__ attached
__Players affected by issue(s):__ red
__Time of issue(s):__ 14:46
__Description of issue(s):__ Buying lifes is still possible when the mine is at full 50 lifes, but does not give any additional life or any other benefit.

I'm not 100% sure if this is a bug, but I would at least expect that the amount of gold wasted this way was tracked and displayed at the end of the game, if this is intended behavior.

[GemTD+ bugreport.zip](https://github.com/nvs/gem/files/671564/GemTD.bugreport.zip)

**Comment by nvs** [comment]
I know what the problem is without looking at the code. This is a long-standing issue that has been in Gem for ages. There is no check when buying lives, and as such gold is essentially wasted. Similar behavior was previously encountered when using extra chance, albeit that was fixed.

This should be relatively simple to resolve.

_Edit: The expected behavior, as far as I see it, is that gold should be refunded if the cap is reached. Ideally, a player would be unable to continue buying lives at all (the ability disabled) when the cap is reached. However, that would require a bit more work to accomplish; but, I do not see that as impossible down the line._
