### ISSUE TITLE
A command to show partially complete special towers

### ISSUE THREAD

**Issue by AndersenJ** [nvs/gem#333]
I think it would be helpful to have a command such as `-combos` or something that would list out which partially-complete towers the players could finish. Example output might be:

```
Malachite: Chipped Opal, Chipped Emerald, Chipped Aquamarine
Star Ruby: Chipped Amethyst, Chipped Ruby, Flawed Ruby
```

The gems the player already has on the field could be color coded, giving the player an easy indicator of what they need. Perhaps gems which are not already owned but can currently be selected to keep could also be color coded.

If this is a feature others want, but nobody feels like implementing it, I could probably implement it. I've never done any coding with Warcraft III's engine, but I have experience with other languages.

**Comment by nvs** [comment]
Hey, thanks for the suggestion. A bit of thought has already been put into this exact issue, and I see two potential options:

- Either using objects and/or object levels (#23);
- Or, multiple boards (#252).

Neither option is mutually exclusive. In fact, I want to do both eventually. Regardless, a bit of work in other areas is required. For example, the internal state of Gem Combination needs to be exposed. However, I am not a fan of new text commands. I have no plans to add any unless absolutely necessary, and this issue doesn't fit the bill.

For me, the priority on this issue is low, even though I realize that adding polish to the map would improve its image. If you want to give it a shot, I'll assist however I can. I'm in the process of reworking the build process (see [nvs/map](https://github.com/nvs/map/projects/3)), as well as contemplating using [Wurst](https://wurstscript.github.io/) for further development.

## Object Tooltips

The tooltips on the units need improvement across the board. [This comment](23#issuecomment-274330869) talk about dynamic tooltips, which are impossible in Warcraft 3. However, they can be simulated by using multiple objects and/or object levels. This behavior does bring a potential (unverified) concern over map loading time (i.e. players that load too slowly will be dropped). 

Editing SLK data directly does seem to present a workaround (see [this comment](23#issuecomment-263418016)). However, I would prefer to have a built map fully auditable within the World Editor, so this is most likely off the table.

The use of either abilities or items does bring the option of having a clickable event highlight the actual units in-game for the player, so that's a plus.

## Multiple Boards

Multiple boards (#252) that players can cycle through (similar to YouTD) is probably easiest to implement, and closest to what you actually suggested. A player could hit the escape key to get a board that displays information about their progress towards combinations. This is a much simpler way to approach the issue, and probably where I would start on this issue.

**Comment by nvs** [comment]
I believe a native was introduced in 1.29.0 that allows editing tooltips in game. However, it may have some issues. I will need to look into this as another possible solution.

**Comment by nvs** [comment]
For an on unit option, the native `BlzSetAbilityTooltip ()` (and its related natives) work at the ability id level. Multiple units would have the same ability. To make use of this native, each player would need their own copy (or level) of an ability. This quickly become unwieldy if more than eight players are supported.

An alternative would be to add inventory to all gems. Then they can have an item that should be modifiable by `BlzSetItemTooltip ()`. This has not been tested. But, I'm thinking that each item can be handled uniquely. This is much simpler to implement and handle.

Of course, a multiboard option still remains.

**Comment by nvs** [comment]
Closing this issue as a duplicate. At this point, #450 has a more fleshed out plan to address the matter.
