### ISSUE TITLE
Chipped gem still at MAX Quality Level

### ISSUE THREAD

**Issue by ry1015** [nvs/gem#413]
version 1.5.4

Extra (Opal 3x and above)

Chipped opals were given. Both at 3x and 4x.

**Comment by nvs** [comment]
This is a fully intended part of the design, introduced in [1.5.0]. In the rework, new pros and cons were added to Extra Chance. This is one of the cons. Most noticeable to players would be that pieces of slates, rather than the slates themselves, are offered via Extra Chance. Now, I am still looking at numbers and planning some tweaks down the line. But getting Chipped from using Extra Chance for Perfects will remain.

I should add that without Extra Chance active, it is not possible to get Chipped. Only when you use it for Perfects do Chipped come back into the equation.

Note this part of the Changelog (emphasis added):

> - For Perfects:
>   - Sets the target to the selected Perfect, increasing chances to get **all** qualities of the chosen type.

[1.5.0]: https://github.com/nvs/gem/blob/master/docs/changelog.md#150---2018-11-16
