### ISSUE TITLE
Gem TD+ 1.6.13 bug???

### ISSUE THREAD

**Issue by StevenElev11n** [nvs/gem#548]
Some to towers/mazing rocks disappeared during games. It happened to a few games. Does anyone know what is the issue and how to fix them?

**Comment by nvs** [comment]
You need to provide more information. Screenshots, and ideally replays. Otherwise, there is not much information to go on.

Now, a common issue some people run into is if they try to micro their towers and use `Attack` click. They can accidentally destroy their own structures. If this sounds like a possibility, consider only right clicking, and relying on the smart behavior.

**Comment by 7Elev11n** [comment]
I think you are right. I played a game without any micro-control "attack click" and there was not any disappearance of towers/rocks. You mentioned "only right clicking", does that mean no micro-control or only right clicking on towers?
Thank you very much for your reply.

**Comment by nvs** [comment]
What I mean is that when you order your towers, you simply right click using the mouse. This is a smart order, as handled by Warcraft III, and will attack only enemies and not friendlies.

**Comment by 7Elev11n** [comment]
Thank you very much for your clarification. I really appreciate your work and enjoy the game very much.

**Comment by nvs** [comment]
If you think that was the source of your problem, you can go ahead and close this issue. Otherwise, I'll close it in a few days  if I don't hear anything.
